### PR TITLE
avoid grep to interpret options passed as patterns. Eg: --help

### PR DESCRIPTION
**Pull request by jotadrilo**

### CODE REVIEW

**Review by joseajp — APPROVED** [review]
😊

**Comment by dgonzalezruiz** [comment]
Why does this man get a smiling face and all I get is rejection? 😭

**Comment by jotadrilo** [comment]
I'm prettier

**Comment by andresbono** [comment]
@dgonzalezruiz, we all are proud of you adding the first PR (#1). A gold medal for you: :1st_place_medal:

**Review by andresbono — APPROVED** [review]
Thanks for your contribution! ☃️

**Pull request merged**
